server:
  port: 8000

spring:
  application:
    name: jpapractice

  config:
    activate:
      on-profile: dev

  # MariaDB Setting
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      # create, create-drop, update, none
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # Redis Setting
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 6000ms

  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}