server:
  port: 8761  # Eureka Server의 기본 포트

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false  # Eureka Server에 등록 여부
    fetch-registry: false  # Eureka Server에 등록된 서비스들의 정보를 가져올지 여부