server:
#  port: 0
  port: 60000 # 실습 편의상 60000번으로 고정

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
#      password: password
      password: $2a$10$g70rRcQBR7Jnm9A9m/Nqje8lCIPeADz2.VBMxhPyzUBoJc28pvC9.

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true # 호스트명 대신 IP로 등록
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.