SELECT	*
FROM		employee;


-- 나승원 사원과 같은 직급이고 많은 급여를 받는 사원의 정보 조회
-- WHERE절의 서브쿼리
SELECT	*
FROM		employee
WHERE		JOB_ID = (
	SELECT	JOB_ID
	FROM		EMPLOYEE
	WHERE		EMP_NAME = '나승원'
)
AND SALARY > (
	SELECT	SALARY
	FROM		EMPLOYEE
	WHERE		EMP_NAME = '나승원'
);


-- 부서별 급여 총합이 가장 높은 부서의 부서명과 급여 총합 조회
-- FROM절의 서브쿼리
SELECT	V.DEPT_NAME
			, MAX(V.SUM)
FROM (
	SELECT	SUM(E.SALARY) AS 'SUM'
				, D.DEPT_NAME
	FROM		employee E
	JOIN		department D ON(E.DEPT_ID = D.DEPT_ID)
	GROUP BY D.DEPT_NAME
) V


SELECT	D.DEPT_NAME
			, V.SUM
FROM		department D
JOIN		employee E USING(DEPT_ID)
GROUP BY	D.DEPT_NAME
HAVING	V.SUM IN (
	SELECT	SUM(E.SALARY) AS 'SUM'
				, RANK() OVER(ORDER BY SUM(E.SALARY)) AS '순위'
	FROM		department D
	JOIN		employee E USING(DEPT_ID)
	GROUP BY	D.DEPT_NAME
) V
WHERE V.순위 = 1;


SELECT	*
FROM 		employee
WHERE 	SALARY = (
	SELECT	MIN(SALARY)
	FROM		employee
);


-- 부서별 최소 급여를 받는 사원의 이름, 부서명, 급여 조회
SELECT	E.EMP_NAME
			, D.DEPT_NAME
			, E.SALARY
FROM		employee E
JOIN		department D ON (E.DEPT_ID = D.DEPT_ID)
WHERE (E.DEPT_ID, E.SALARY) IN (
	SELECT	DEPT_ID
				, MIN(SALARY)
	FROM		employee E
	GROUP BY DEPT_ID
)
ORDER BY 1;


SELECT	SUB.EMP_NAME
			, SUB.DEPT_NAME
			, SUB.SALARY
FROM	(
	SELECT	E.EMP_NAME
				, D.DEPT_NAME
				, E.SALARY
				, RANK() OVER(PARTITION BY E.DEPT_ID ORDER BY E.SALARY) AS 'RNK'
	FROM		employee E
	JOIN		department D ON (E.DEPT_ID = D.DEPT_ID)
) SUB
WHERE		SUB.RNK = 1
ORDER BY 1;


-- 과장의 급여 조회
SELECT	EMP_NAME
			, JOB_ID
			, SALARY
FROM		employee E
WHERE JOB_ID = (
	SELECT	JOB_ID
	FROM		JOB
	WHERE		JOB_TITLE = '과장'
);


-- 대리의 급여 조회
SELECT	EMP_NAME
			, JOB_ID
			, SALARY
FROM		employee E
WHERE JOB_ID = (
	SELECT	JOB_ID
	FROM		JOB
	WHERE		JOB_TITLE = '대리'
);


-- 다중행 서브쿼리(ANY, ALL)
SELECT	E.EMP_NAME
			, E.SALARY
FROM		employee E
JOIN		job J ON (E.JOB_ID = J.JOB_ID)
WHERE		J.JOB_TITLE = '대리'
AND		SALARY > ANY (
	SELECT	E.SALARY
	FROM		employee E
	JOIN		job J ON (E.JOB_ID = J.JOB_ID)
	WHERE		J.JOB_TITLE = '과장'
);


SELECT	E.EMP_NAME
			, E.SALARY
FROM		employee E
JOIN		job J ON (E.JOB_ID = J.JOB_ID)
WHERE		J.JOB_TITLE = '대리'
AND		SALARY < ANY (
	SELECT	E.SALARY
	FROM		employee E
	JOIN		job J ON (E.JOB_ID = J.JOB_ID)
	WHERE		J.JOB_TITLE = '과장'
);


SELECT	E.EMP_NAME
			, E.SALARY
FROM		employee E
JOIN		job J ON (E.JOB_ID = J.JOB_ID)
WHERE		J.JOB_TITLE = '대리'
AND		SALARY > ALL (
	SELECT	E.SALARY
	FROM		employee E
	JOIN		job J ON (E.JOB_ID = J.JOB_ID)
	WHERE		J.JOB_TITLE = '과장'
);


SELECT	E.EMP_NAME
			, E.SALARY
FROM		employee E
JOIN		job J ON (E.JOB_ID = J.JOB_ID)
WHERE		J.JOB_TITLE = '대리'
AND		SALARY < ALL (
	SELECT	E.SALARY
	FROM		employee E
	JOIN		job J ON (E.JOB_ID = J.JOB_ID)
	WHERE		J.JOB_TITLE = '과장'
);


-- TOP N QUERY: LIMIT ~ OFFSET
SELECT	E.DEPT_ID
			, SUM(E.SALARY)
FROM		employee E
GROUP BY DEPT_ID
ORDER BY 2 DESC
LIMIT 1;


SELECT	E.DEPT_ID
			, SUM(E.SALARY)
FROM		employee E
GROUP BY DEPT_ID
ORDER BY 2 DESC
LIMIT 3 OFFSET 0;


-- 자기 직급의 평균 급여를 받는 직원의 이름, 직급명, 급여 조회(급여는 정수 5자리까지)
SELECT	E.EMP_NAME
			, J.JOB_TITLE
			, E.SALARY
FROM		job J
JOIN		employee E USING (JOB_ID)
WHERE (J.JOB_ID, E.SALARY) IN (
	SELECT	JOB_ID
				, TRUNCATE(AVG(SALARY), -5)
	FROM		employee
	GROUP BY JOB_ID
);


-- INLINE VIEW로 만들어진 가상 테이블은 실제 테이블이랑 JOIN 가능
SELECT	E.EMP_NAME
			, J.JOB_TITLE
			, E.SALARY
FROM	(
	SELECT	JOB_ID
				, TRUNCATE(AVG(SALARY), -5) AS JOBAVG
	FROM		employee
	GROUP BY JOB_ID
) V
JOIN employee E ON (V.JOB_ID = E.JOB_ID AND V.JOBAVG = E.SALARY)
JOIN job J ON (E.JOB_ID = J.JOB_ID);


-- 상호연관 서브쿼리
SELECT	E.EMP_NAME
			, J.JOB_TITLE
			, E.SALARY
FROM		job J
JOIN		employee E USING (JOB_ID)
WHERE E.SALARY = (
	SELECT	TRUNCATE(AVG(SALARY), -5)
	FROM		employee EE
	WHERE		EE.JOB_ID = E.JOB_ID
);


-- DDL
DROP DATABASE IF EXISTS TABLEDB;
CREATE DATABASE TABLEDB;

USE TABLEDB;

DROP TABLE IF EXISTS TB_BLOG;
CREATE TABLE TB_BLOG(
	POST_ID		VARCHAR(50) PRIMARY KEY,
	TITLE			VARCHAR(100),
	CONTENT		VARCHAR(100),
	EMAIL			VARCHAR(100),
	CREATE_AT	DATE
	-- PRIMARY KEY	(POST_ID)
);

SELECT	*
FROM		tb_blog;


-- DML
INSERT INTO tb_blog(POST_ID, TITLE, CONTENT, EMAIL, CREATE_AT)
VALUES('1', 'TITLE1', 'CONTENT1', 'test email', NOW());


DROP TABLE IF EXISTS TB_BLOG;
CREATE TABLE TB_BLOG(
	POST_ID		VARCHAR(50) PRIMARY KEY,
	TITLE			VARCHAR(100),
	CONTENT		VARCHAR(100),
	EMAIL			VARCHAR(100),
	CREATE_AT	DATE DEFAULT NOW()
	-- PRIMARY KEY	(POST_ID)
);

SELECT	*
FROM		tb_blog;

INSERT INTO tb_blog(POST_ID, TITLE, CONTENT, EMAIL)
VALUES('1', 'TITLE1', 'CONTENT1', 'test email');


-- 기본키에 NULL을 넣으면 안됨
INSERT INTO tb_blog(POST_ID, TITLE, CONTENT, EMAIL)
VALUES(NULL, 'TITLE1', 'CONTENT1', 'test email');


DROP TABLE IF EXISTS TB_BLOG;
CREATE TABLE TB_BLOG(
	POST_ID		VARCHAR(50) PRIMARY KEY,
	TITLE			VARCHAR(100),
	CONTENT		VARCHAR(100),
	EMAIL			VARCHAR(100),
	CATEGORY		VARCHAR(20) CHECK(CATEGORY IN ('C1', 'C2', 'C3', 'C4')),
	CREATE_AT	DATE DEFAULT NOW()
	-- PRIMARY KEY	(POST_ID)
);

INSERT INTO tb_blog(POST_ID, CATEGORY)
VALUES('1', 'C3');

SELECT	*
FROM		tb_blog;