USE tabledb;

CREATE TABLE TB_JOB (
	JOB_ID 		VARCHAR(10),
	JOB_TITLE	VARCHAR(50),
	PRIMARY KEY(JOB_ID)
);
INSERT INTO TB_JOB(JOB_ID, JOB_TITLE)
VALUES('J1', '대표이사');
INSERT INTO TB_JOB(JOB_ID, JOB_TITLE)
VALUES('J2', '상무');
SHOW INDEX FROM TB_JOB;


CREATE TABLE TB_DEPT (
	DEPT_ID	VARCHAR(10),
	DEPT_TITLE VARCHAR(50),
	PRIMARY KEY(DEPT_ID)
);
INSERT INTO TB_DEPT(DEPT_ID, DEPT_TITLE)
VALUES('10', '교육팀');
INSERT INTO TB_DEPT(DEPT_ID, DEPT_TITLE)
VALUES('20', '운영팀');
SHOW INDEX FROM TB_DEPT;


CREATE TABLE TB_EMP (
	EMP_ID VARCHAR(10) PRIMARY KEY,
	EMP_NAME VARCHAR(50) NOT NULL,
	HIRE_DATE DATE DEFAULT SYSDATE(),
	DEPT_ID VARCHAR(10) NOT NULL REFERENCES TB_DEPT(DEPT_ID),
	JOB_ID VARCHAR(10) NOT NULL,
	-- FOREIGN KEY(DEPT_ID) REFERENCES TB_DEPT(DEPT_ID) ON DELETE CASCADE,
	FOREIGN KEY(JOB_ID) REFERENCES TB_JOB(JOB_ID) ON UPDATE CASCADE
);
SHOW INDEX FROM TB_EMP;
/*
ERROR
INSERT INTO TB_EMP(EMP_ID, EMP__NAME, DEPT_ID, JOB_ID)
VALUES('100', 'JIM', NULL, NULL);

INSERT INTO TB_EMP(EMP_ID, EMP__NAME, DEPT_ID, JOB_ID)
VALUES('100', 'JIM', 30, 'J3');
*/

INSERT INTO TB_EMP(EMP_ID, EMP__NAME, HIRE_DATE, DEPT_ID, JOB_ID)
VALUES('200', 'JIM', DEFAULT, '10', 'J1');

INSERT INTO TB_EMP(EMP_ID, EMP__NAME, HIRE_DATE, DEPT_ID, JOB_ID)
VALUES
('300', 'JIM', NULL, '10', 'J1'),
('300', 'JIM', NULL, '10', 'J1'),
('300', 'JIM', NULL, '10', 'J1');

SELECT * FROM TB_EMP;


DELETE FROM TB_DEPT
WHERE DEPT_ID = '10';

SELECT * FROM TB_DEPT;
SELECT * FROM TB_EMP;

/*
NOT NULL은 테이블 레벨로 제약을 못 검
CREATE TABLE TB_EMPLOYEE(
	EMP_ID VARCHAR(10),
	EMP_NAME VARCHAR(50),
	NOT NULL(EMP_NAME)
);
*/
DROP TABLE IF EXISTS TB_EMPLOYEE;
CREATE TABLE TB_EMPLOYEE(
	EMP_ID VARCHAR(10),
	EMP_NAME VARCHAR(50) NOT NULL,
	SALARY INT CHECK(SALARY > 0),
	GENDER CHAR(10) CHECK(GENDER IN ('F', 'M')),
	HIRE_DATE DATE DEFAULT SYSDATE(),
	JOB_ID VARCHAR(10),
	DEPT_ID VARCHAR(10)
);
SHOW INDEX FROM TB_EMPLOYEE;
SELECT * FROM TB_EMPLOYEE;


-- ALTER
ALTER TABLE TB_EMPLOYEE
ADD CONSTRAINT PRIMARY KEY(EMP_ID);
SHOW INDEX FROM TB_EMPLOYEE;

ALTER TABLE TB_EMPLOYEE
MODIFY COLUMN DEPT_ID VARCHAR(10) NOT NULL,
MODIFY COLUMN JOB_ID VARCHAR(10) NOT NULL,
ADD CONSTRAINT FOREIGN KEY(DEPT_ID) REFERENCES TB_DEPT(DEPT_ID),
ADD CONSTRAINT FOREIGN KEY(JOB_ID) REFERENCES TB_JOB(JOB_ID);

/*
VIEW
CREATE OR REPLACE VIEW VIEW_NAME(ALIAS)
AS SUBQUERY;
*/
USE TESTDB;

CREATE OR REPLACE VIEW EMP_VIEW(NAME, DEPT)
AS
SELECT	E.EMP_NAME
			, D.DEPT_NAME
FROM		DEPARTMENT D
JOIN		EMPLOYEE E ON(D.DEPT_ID = E.DEPT_ID)
WHERE		E.DEPT_ID = '90';

SELECT * FROM emp_view;


-- UPDATE
UPDATE	department
SET 		DEPT_NAME = '전략기획팀'
WHERE		DEPT_ID = '90';

SELECT * FROM department;


UPDATE	employee
SET	JOB_ID = (
			SELECT	JOB_ID
			FROM employee
			WHERE EMP_NAME = '성혜교'
		),
		DEPT_ID = (
			SELECT	DEPT_ID
			FROM employee
			WHERE EMP_NAME = '성혜교'
		)
WHERE EMP_NAME = '심하균';

SELECT * FROM employee;


UPDATE	employee
SET		MARRIAGE = DEFAULT
WHERE		EMP_NAME = '한선기';

SELECT * FROM employee;


UPDATE	employee
SET		BONUS_PCT = 0.3
WHERE		DEPT_ID = (
				SELECT	DEPT_ID
				FROM		department
				WHERE DEPT_NAME = '해외영업2팀'
			);
			
SELECT	EMP_NAME
			, BONUS_PCT
FROM		employee
WHERE 	DEPT_ID = (
				SELECT	DEPT_ID
				FROM		department
				WHERE DEPT_NAME = '해외영업2팀'
			);
			

-- SEQUENCE
CREATE SEQUENCE SEQ;
SELECT NEXTVAL(SEQ);
SELECT LASTVAL(SEQ);

DROP SEQUENCE SEQ;


CREATE SEQUENCE SEQ
START WITH 1000
INCREMENT BY 3
MAXVALUE 1012;

CREATE TABLE TB_TEMP(
TEMPNUM INT DEFAULT(NEXTVAL(SEQ)) PRIMARY KEY,
CUSTOMER VARCHAR(50)
);

INSERT INTO TB_TEMP(CUSTOMER) VALUES('SSS');
INSERT INTO TB_TEMP(CUSTOMER) VALUES('SSS');
INSERT INTO TB_TEMP(CUSTOMER) VALUES('SSS');
INSERT INTO TB_TEMP(CUSTOMER) VALUES('SSS');

SELECT * FROM TB_TEMP;