ALTER TABLE SPRING_USER_TBL
ADD CONSTRAINT PRIMARY KEY(EMAIL);

SELECT * FROM spring_user_tbl;


CREATE SEQUENCE POSTID
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE SPRING_POST_TBL(
ID INT DEFAULT NEXTVAL(POSTID) PRIMARY KEY,
TITLE VARCHAR(50) NOT NULL,
CONTENT VARCHAR(200) NOT NULL,
CATEGORY VARCHAR(50) CHECK(CATEGORY IN ('개발', '생활', '취미', '일상')),
EMAIL VARCHAR(50) REFERENCES spring_user_tbl(EMAIL)
);

SELECT * FROM spring_post_tbl;


CREATE SEQUENCE COMMENTID
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE SPRING_COMMENT_TBL(
COMMENT VARCHAR(200) NOT NULL,
POSTID INT REFERENCES SPRING_POST_TBL(ID),
EMAIL VARCHAR(50) REFERENCES spring_user_tbl(EMAIL),
ID INT DEFAULT NEXTVAL(COMMENTID) PRIMARY KEY
);

SELECT * FROM SPRING_COMMENT_TBL;
