SELECT	*
FROM		tb_department;

SELECT	*
FROM		tb_student;

SELECT	*
FROM		tb_professor;

SELECT	*
FROM		tb_class;

-- 문제 1번
SELECT	DEPARTMENT_NAME AS '학과 명',
			CATEGORY AS '계열'
FROM		tb_department;


-- 문제 2번
SELECT	CONCAT(DEPARTMENT_NAME, '의 정원은 ', CAPACITY, '명 입니다.') AS '학과별 정원'
FROM		tb_department;


-- 문제 3번
SELECT	STUDENT_NAME
FROM		tb_student
WHERE		ABSENCE_YN = 'Y'
AND 		DEPARTMENT_NO = (
	SELECT	DEPARTMENT_NO
	FROM		TB_DEPARTMENT
	WHERE 	DEPARTMENT_NAME = '국어국문학과'
)
AND		STUDENT_SSN LIKE '%-2%';


-- 문제 4번
SELECT	STUDENT_NAME
FROM		tb_student
WHERE		STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');


-- 문제 5번
SELECT	DEPARTMENT_NAME, CATEGORY
FROM		tb_department
WHERE		CAPACITY BETWEEN 20 AND 30;


-- 문제 6번
SELECT	PROFESSOR_NAME
FROM		tb_professor
WHERE		ISNULL(DEPARTMENT_NO);


-- 문제 7번
SELECT	COUNT(*)
FROM		tb_department
WHERE		ISNULL(DEPARTMENT_NO);


-- 문제 8번
SELECT	CLASS_NO
FROM		tb_class
WHERE		ISNULL(PREATTENDING_CLASS_NO) = 0;


-- 문제 9번
SELECT	DISTINCT CATEGORY
FROM		tb_department;


-- 문제 10번
SELECT	STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM		tb_student
WHERE		ENTRANCE_DATE LIKE '2002%'
AND		ABSENCE_YN = 'N'
AND		STUDENT_ADDRESS LIKE '%전주%';


-- 문제 1번
SELECT	STUDENT_NO AS '학번',
			STUDENT_NAME AS '이름',
			ENTRANCE_DATE AS '입학년도'
FROM		tb_student
WHERE		DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;


-- 문제 2번
SELECT	PROFESSOR_NAME,
			PROFESSOR_SSN
FROM		tb_professor
WHERE		CHAR_LENGTH(PROFESSOR_NAME) != 3;


-- 문제 3번
SELECT	PROFESSOR_NAME AS '교수 이름',
			CAST(YEAR(NOW()) AS INT) - CAST(CONCAT('19', SUBSTRING(PROFESSOR_SSN, 1, 2)) AS INT) + 1 AS '나이'
FROM		tb_professor
WHERE		SUBSTRING(PROFESSOR_SSN, 8, 1) IN ('1', '3')
ORDER BY	나이;


-- 문제 4번
SELECT	RIGHT(PROFESSOR_NAME, 2) AS '이름'
FROM		tb_professor;


-- 문제 5번
SELECT	STUDENT_NO,
			STUDENT_NAME
FROM		tb_student
WHERE		CAST(LEFT(ENTRANCE_DATE, 4) AS INT) - CAST(CONCAT('19', LEFT(STUDENT_SSN, 2)) AS INT) > 19;


-- 문제 6번
-- WEEKDAY(): 요일을 숫자로 반환(월요일이 0)
SELECT	CASE WEEKDAY('2020-12-25')
				WHEN 0 THEN '월요일'
				WHEN 1 THEN '화요일'
				WHEN 2 THEN '수요일'
				WHEN 3 THEN '목요일'
				WHEN 4 THEN '금요일'
				WHEN 5 THEN '토요일'
				WHEN 6 THEN '일요일'
				ELSE '?'
			END AS '2020년 크리스마스';


-- 문제 8번
SELECT	STUDENT_NO,
			STUDENT_NAME
FROM		tb_student
WHERE		LEFT(STUDENT_NO, 1) != 'A';


-- 문제 9번
SELECT	ROUND(AVG(POINT), 1) AS '평점'
FROM		TB_GRADE
WHERE		STUDENT_NO = 'A517178';


-- 문제 11번
SELECT	COUNT(*)
FROM		tb_student
WHERE		COACH_PROFESSOR_NO IS NULL;


-- 문제 12번
SELECT	ROUND(AVG(POINT), 1)
FROM		tb_grade
WHERE		STUDENT_NO = 'A112113'
GROUP BY	LEFT(TERM_NO, 4);


-- 문제 13번
SELECT	DEPARTMENT_NO AS '학과코드명',
			COUNT(ABSENCE_YN = 'Y') AS '휴학생 수'
FROM		tb_student
GROUP BY DEPARTMENT_NO;


-- 문제 14번
SELECT	STUDENT_NAME AS '동일이름',
			COUNT(STUDENT_NAME) AS '동명인 수'
FROM		tb_student
GROUP BY	STUDENT_NAME
HAVING	COUNT(STUDENT_NAME) > 1;